// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6KF-_kKCO5N29S2fqhmBqjZzZC_7aE64',
    appId: '1:556754972247:web:1365a9eec177d7ca8e7d12',
    messagingSenderId: '556754972247',
    projectId: 'taptag-db',
    authDomain: 'taptag-db.firebaseapp.com',
    storageBucket: 'taptag-db.firebasestorage.app',
    measurementId: 'G-D0B9SL2X3J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCa5Vs61q2Pl4E4Gvc5H3IW7aHGPEwFJtY',
    appId: '1:556754972247:android:d9805e91358c3a8b8e7d12',
    messagingSenderId: '556754972247',
    projectId: 'taptag-db',
    storageBucket: 'taptag-db.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6KF-_kKCO5N29S2fqhmBqjZzZC_7aE64',
    appId: '1:556754972247:web:0be880688ff142958e7d12',
    messagingSenderId: '556754972247',
    projectId: 'taptag-db',
    authDomain: 'taptag-db.firebaseapp.com',
    storageBucket: 'taptag-db.firebasestorage.app',
    measurementId: 'G-ZMW23GFLFL',
  );
}
